Convert Rnw vignette to Rmd and bump version
Bioconductor/zlibbioc pull request #2
Opened 2022-01-25 22:56 UTC by jwokaty

2022-01-25 22:59 UTC, jwokaty commented
@LiNk-NY Could I ask you to look at my commit to change zlibbioc's Rnw to Rmd? I did everything manually and compared the output of the existing vignette with the output of the one I created.

2022-01-25 23:02 UTC, LiNk-NY requested changes
It looks good. Perhaps format the bash code with triple backticks ``` and omit the extra stuff i.e., `{bash ...}`

2022-01-25 23:02 UTC, LiNk-NY commented on DESCRIPTION
> +Imports: BiocStyle
This should be `Suggests`.

2022-01-25 23:02 UTC, LiNk-NY commented on vignettes/UsingZlibbioc.Rmd
> +> install.packages("zlibbioc_<...>.tar.gz",
You can omit the `>` here

2022-01-25 23:02 UTC, LiNk-NY commented on vignettes/UsingZlibbioc.Rmd
> +The *Rsamtools* package is a more complex example illustrating this approach.
Perhaps add a link to the package via `r Biocpkg('Rsamtools')`

2022-02-01 18:48 UTC, LiNk-NY approved these changes

2022-02-23 20:34 UTC, merged